### ISSUE TITLE
Param file is not getting produced

### ISSUE THREAD

**Issue by kvshams** [ne1s0n/MTGOsc#2]
I tried the tool and getting an error while calling `MTGO`
`call.MTGO(outfolder = root, verbose = TRUE)`
```
======> MTGO executed with the following OUTPUT:

======> MTGO executed with the following ERRORS:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.io.FileNotFoundException: /home/shams/sc_rna/mtgosc/params.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at it.ReadParameters.readFileParam(ReadParameters.java:33)
	at it.ReadParameters.<init>(ReadParameters.java:27)
	at it.MainClassPesi.main(MainClassPesi.java:17)
	... 5 more
```

I the output folder and there is not file produced with missing param file.

These are the files in the output folder produced until `call.MTGO`.
`GO.txt  MTGO.err.txt  MTGO.out.txt  coexpression_full.tsv  edges.tsv`

**Comment by Danila145** [comment]
Hi kvshams,
I'm the developer of MTGO, I suggest you to download MTGO directly from https://gitlab.com/d1vella/MTGO. Here you can found the manual with the instructions and the directory "Sample" with files of example to execute MTGO!
I think your error is about file param.txt, in the version MTGO (not scMTGO) there isn't any param file, you can insert parameters directly on interface so I hope you can solve your problem! 
Let me know!
Sorry for the late! I will answer soon to your next question!
Good luck!

**Comment by Danila145** [comment]
Try this link:
https://rdrr.io/github/ne1s0n/MTGOsc/
